export type BaseProduct =  {
    feed_product_type: string,
    item_sku: string,
    update_delete: string,
    brand_name: string,
    item_name: string,
    recommended_browse_nodes: string,
    product_description: string,
    part_number: string,
    manufacturer: string,
    quantity:number,
    standard_price:number,
    main_image_url:string,
    other_image_url1:string,
    other_image_url2:string,
    other_image_url3:string,
    other_image_url4:string,
    other_image_url5:string,
    other_image_url6:string,
    other_image_url7:string,
    other_image_url8:string,
    relationship_type:string,
}